#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/FreeNetworkMonitor
npm i --force
npm run build
mkdir -p ./out/images
mkdir -p ./out/blogpics
cp -r ../FreeNetworkMonitorBlog/public/images ./out/
cp -r ../FreeNetworkMonitorBlog/public/blogpics ./out/
docker compose -f docker-compose.yml build
docker push mungert/networkmonitorreact:1.0.0
