#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/FreeNetworkMonitor
npm update
npm audit
npm run build
docker compose -f docker-compose-local.yml build
docker push mungert/networkmonitorreact-local:0.2.0 
