#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/FreeNetworkMonitor
npm update
npm audit
npm run build
docker compose build
docker push mungert/networkmonitorreact:0.2.0 
