#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/FreeNetworkMonitor
npm i --force
npm audit
npm run build
rm -r ./out
cd ../FreeNetworkMonitorBlog
git pull https://mungert69:$value@github.com/Mungert69/FreeNetworkMonitorBlog
npm i 
npm run export
cp -r ./out ../FreeNetworkMonitor/
cd ../FreeNetworkMonitor
docker compose -f docker-compose.yml build
docker push mungert/networkmonitorreact:0.8.0

